### PR TITLE
[source-kafka] Fix error handling for kubeconfig

### LINKED ISSUE #58: [source-kafka] Fix error handling for kubeconfig
see https://github.com/knative/client-contrib/pull/33#discussion_r446014741

### PR DESCRIPTION
**Pull request by daisy-ycguo**
Closes #58 

The PR is to fix error handling of kubeconfig, including a dependency library upgrade.

### CODE REVIEW

File: plugins/source-kafka/pkg/client/client.go [hunk 1]
```diff
@@ -28,22 +28,19 @@ import (
 )
 
 type kafkaSourceClient struct {
-	kafkaSourceParams *types.KafkaSourceParams
-	client            clientv1alpha1.SourcesV1alpha1Interface
 	namespace         string
+	kafkaSourceParams *types.KafkaSourceParams
 	knSourceClient    sourcetypes.KnSourceClient
```
Comment (navidshaikh) [inline plugins/source-kafka/pkg/client/client.go:33]: IMO  we should rename this to  `PluginSourceClient` to better reflect the scope and clear separation with core kn clients. (could be done in a separate PR). WDYT ?

File: plugins/source-kafka/pkg/client/client.go [hunk 2]
```diff
@@ -64,7 +61,11 @@ func (c *kafkaSourceClient) KafkaSourceParams() *types.KafkaSourceParams {
 
 //CreateKafkaSource is used to create an instance of KafkaSource
 func (c *kafkaSourceClient) CreateKafkaSource(kafkaSource *v1alpha1.KafkaSource) error {
-	_, err := c.client.KafkaSources(c.namespace).Create(kafkaSource)
+	sourceClient, err := c.KafkaClient()
+	if err != nil {
+		return knerrors.GetError(err)
+	}
```
Comment (navidshaikh) [inline plugins/source-kafka/pkg/client/client.go:67]: I think we should raise this error in `NewKafkaSourceClient` function itself while creating the client.
So, `NewKafkaSourceClient` handles any error for creating the client while `CreateKafkaSource` could be focused on any error raised while creating source itself.

This will also prevent repetition of this error handling in each CREATE/GET/DELETE.

File: plugins/source-kafka/pkg/client/client.go (hunk 1 above)
Comment (maximilien) [reply plugins/source-kafka/pkg/client/client.go:33]: Makes sense. But this comes from the common code. Let’s do these change when I move the `kn-source-pkg` code. Cool?

File: plugins/source-kafka/pkg/factories/source_factory.go [hunk 3]
```diff
@@ -37,18 +38,21 @@ func NewKafkaSourceFactory() types.KafkaSourceFactory {
...
 	return &kafkaClientFactory{
 		kafkaSourceParams: fakeParams,
 		kafkaSourceClient: fakeSourceClient,
 		knSourceFactory:   sourcefactories.NewDefaultKnSourceFactory(),
 	}
 }
 
-func (f *kafkaClientFactory) CreateKafkaSourceClient(namespace string) types.KafkaSourceClient {
+// boilerplate
+
```
Comment (maximilien) [inline plugins/source-kafka/pkg/factories/source_factory.go:52]: I would move all boilerplate code to `boilerplate.go`... that’s the point of these files :)

File: plugins/source-kafka/pkg/client/client.go [hunk 4]
```diff
@@ -144,3 +153,16 @@ func (b *KafkaSourceBuilder) Sink(sink *duckv1.Destination) *KafkaSourceBuilder
 func (b *KafkaSourceBuilder) Build() *v1alpha1.KafkaSource {
 	return b.kafkaSource
 }
+
+// private
```
[the remark this answers is not in the document]
Comment (daisy-ycguo) [reply plugins/source-kafka/pkg/client/client.go:157]: removed the comment.

File: plugins/source-kafka/pkg/client/client.go [hunk 5]
```diff
@@ -144,3 +153,16 @@ func (b *KafkaSourceBuilder) Sink(sink *duckv1.Destination) *KafkaSourceBuilder
...
+
+func (c *kafkaSourceClient) KafkaClient() (clientv1alpha1.SourcesV1alpha1Interface, error) {
+	var err error
+	if c.client == nil {
+		c.client, err = c.KafkaSourceParams().NewSourcesClient()
+		if err != nil {
+			return nil, err
```
[the remark this answers is not in the document]
Comment (daisy-ycguo) [reply plugins/source-kafka/pkg/client/client.go:164]: fixed

File: plugins/source-kafka/pkg/client/client.go (hunk 2 above)
Comment (daisy-ycguo) [reply plugins/source-kafka/pkg/client/client.go]: fixed. Please review again.

File: plugins/source-kafka/pkg/factories/source_factory.go (hunk 3 above)
Comment (daisy-ycguo) [reply plugins/source-kafka/pkg/factories/source_factory.go]: done

**Comment by maximilien** [comment]
Looks good to me. Holding to give @navidshaikh a chance for final review. Unhold as you see fit or I will next chance.

/hold
/lgtm
